
spring:
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 192.168.2.166:9876
      bindings:
        input:
          destination: CloudTopic
          group: CloudGroup
        output:
          destination: CloudTopic
server:
  port: 17002
